JS課題②に取り組みました
sora-sea/js-test2 pull request #1
Opened 2021-05-11 01:37 UTC by sora-sea

課題完了しました、ご確認お願い致します。

2021-05-11 13:17 UTC, myzktkyk requested changes
動作については問題ありませんでした！
コードについて何点か指摘がございます 🙏

2021-05-11 13:17 UTC, myzktkyk commented on js/main.js
> +      const div = document.querySelector('div');
変数 `div` が使われている箇所がないようです。
不要であれば削除しましょう。

2021-05-11 13:17 UTC, myzktkyk commented on js/main.js
> +    if ((fizzNum == 0) || (buzzNum == 0)) {
```suggestion
    if ((fizzNum === 0) || (buzzNum === 0)) {
```

比較には `===` を用いて厳密な比較を行いましょう。

2021-05-11 13:17 UTC, myzktkyk commented on js/main.js
> +      const div = document.querySelector('div')
ココも変数 div が使われている箇所がないようです。
不要であれば削除しましょう。

2021-05-13 10:24 UTC, yoshin04 commented on js/main.js
> +      }
いまの記述では、空文字のリストも作られてしまっています。
これは無駄なコードが紛れてしまっているとのことですのでよろしくないです。
fizzbuzzに該当するものだけをリスト化するようにしましょう！

2021-05-15 09:54 UTC, merged